# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

    desc "Deploy a new version to the Google Play"
    lane :deploy do
      gradle(task: "clean")
      # upload_to_play_store
    end

    after_all do |lane|
      # this block is only called if exevuted lane was succcessful
      slack(
        message: "successful deployed new app"
      )
    end

    error do |lane, exception|
      slack(
        message: exception.message,
        success: false
      )
    end
end
